services:
  microwave-api:
    image: alissonmmiquelace/microwave-api:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microwave-network

  microwave-avaloniaui-ui:
    image: alissonmmiquelace/microwave-avaloniaui-ui:latest
    environment:
      - DISPLAY=host.docker.internal:0  
      - PULSE_SERVER=unix:/tmp/pulse-socket  
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  
      - ~/.Xauthority:/root/.Xauthority:ro  
    depends_on:
      - microwave-api
    networks:
      - microwave-network
      
    restart: unless-stopped

networks:
  microwave-network:
    driver: bridge